version: '3'
services:
  web:
    build: .
    volumes:
      - .:/app
    command: python -m pyobo.apps.resolver --data /app/ooh_na_na.tsv.gz --port 5000 --host "0.0.0.0"
    ports:
      - 5000:5000
