version: '3'

services:
  resolver:
    build: .
    environment:
      PYOBO_SQLALCHEMY_URI: postgresql://postgres:pyobo@database:5432/postgres
    command: python -m pyobo.apps.resolver --port 80 --host "0.0.0.0" --sql --gunicorn
    ports:
      - 80:80
    depends_on:
      - database

  database:
    image: pyobo/oohnana:49a70322ff
